build:
  maxIssues: 100

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: false
  ComplexCondition:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  NewLineAtEndOfFile:
    active: false
  FunctionOnlyReturningConstant:
    active: false 